CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_1 "Tone_Moore Clean_DI_1" 5
CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_10 "Tone_Moore Clean_DI_10" 5
CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_1 "Tone_Gravity_DI_1" 5
CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_10 "Tone_Gravity_DI_10" 5
CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_1 "Tone_Rhapsody_DI_1" 5
CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_10 "Tone_Rhapsody_DI_10" 5
CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_1 "Tone_First Compression_DI_1" 5
CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_10 "Tone_First Compression_DI_10" 5
CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_1 "Tone_New Guitar Icon_DI_1" 5
CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_10 "Tone_New Guitar Icon_DI_10" 5
CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_1 "Tone_Room 808_DI_1" 5
CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_10 "Tone_Room 808_DI_10" 5
CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_1 "Tone_Light House_DI_1" 5
CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_10 "Tone_Light House_DI_10" 5
CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_1 "Tone_Dark Soul_DI_1" 5
CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_10 "Tone_Dark Soul_DI_10" 5
CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_1 "Tone_Easy Blues_DI_1" 5
CUDA_VISIBLE_DEVICES=2 ./riffusion_batch_run_inference.sh AudioDI_DI_10 "Tone_Easy Blues_DI_10" 5